route:
  receiver: fanout
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: fanout
    webhook_configs:
      - url: http://fintech_flask:5000/alert
        send_resolved: true
    telegram_configs:
      - bot_token: "$bot-token"
        chat_id: "$chat-id"
        parse_mode: HTML
        message: |-
          ðŸ”” <b>{{ .Status | toUpper }}</b> â€” <b>{{ .CommonLabels.alertname }}</b>
          {{- range .Alerts }}
          â€¢ <b>{{ .Labels.severity }}</b> on <code>{{ .Labels.instance }}</code>
            {{ .Annotations.summary }} â€” {{ .Annotations.description }}
          {{- end }}
        send_resolved: true

